name: Teste Baixar CSV da B3

on:
  schedule:
    - cron: '30 15 * * *'  # Min / Hora
  workflow_dispatch:  # Permite execução manual

jobs:
  baixar-csv:
    runs-on: windows-latest
    permissions:
      contents: write  # Necessário para push

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Importante para histórico do git

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar Chrome e ChromeDriver
        run: |
          choco install googlechrome --no-progress
          choco install chromedriver --no-progress

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager chardet pytz boto3 pandas pyarrow fastparquet

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Rodar script
        run: python scrap.py
        continue-on-error: true  # Opcional: continua mesmo se o script falhar

      - name: Commit e Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv data_parquet/*.parquet logs/download_log.txt logs/buckets3_log.txt || true
          git commit -m "Atualização CSV $(date +'%d-%m-%y')" || echo "Sem mudanças para commit"
          git push
